{% set version = "4.4.1" %}

package:
    name: qutip
    version: {{ version }}

source:
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 3d59a7c67a69617e8222e013a7ed3223870a46855a1a43ab14d97f493a614408

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]
    skip: True                        # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.21
    - scipy >=1.0
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0
    - cython >=0.21

test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
    - nonhermitian
    - ericgig
