appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YpxedqHSCna5xo3v5LY0HjIn3AtpA8u/GsEf4ZOGL00l+KkSw44yMO1wTzygzZGfMsh7N/q7mSfATcyf8M75aboIDPc4Z2W286a03J1yYAqK+dmVEE1KJGwQGSShZGG1hTocymu8z0Vwy8VvDZ5xcQruTB0t7uG8HpNvZCmqdIq2hqquJZ16dzcWZj19WNsaMGuyKh1ohGULmrGq2CMUSsVkVG0uvaEu9ruT1lJ3RppGJbh0MdwyCu2uV6zBSqzHLE6Ihh47U4KoZYcmvfmr1TPWu7Uw4Ggrgy13bCTcc3yCxfOBoVZmkU9JlwaUr3jiM+fhuDpuGOWXosYlBdbsSAu8VVgWHPV3D5QW+mnCwzX30GVHZCt/p5Dhiv97XZETUelcSerinZgdS9DWt4rGpyU/mLiRQ2I1eeLSpafyIz8QuvcdFGUS0/ZDZrSWoqbZD0oa3PJvK8WKc++xnxwooZeuIgA2x7yJA0EkLUlLuNK2KIbk4x5TybeOOdivAnRx7Fev2HmWA6A6iiN3p8vR5mCHpvbHdjNoVUJzp1rgzggij/8DvM+ukDcKSEtCXRn06cNbZn3elvXjCFu5Cf1/yVQVa4o9SEsDdhRLpxHxzxYCe7a2PGgdqCMqyOztO7X+kSYaatLX7jwukcynbm4fNnRQ99fUsBkQPWiy3Kyas68=}
provider:
  win: azure
