travis:
  secure:
    BINSTAR_TOKEN: EBUlOvzk+AxOnb6mt1ZpJKVYbjnYyOl6YHk9VbI9ca3CPgdU3Cr0t9gVM42At2wLRh0di9e8SMME1bIzEHxw8oCVQKPmItxRJQp8Mjj1u4YGer8wh5qWs35kKqmjUzp4zRPHEvS+potrLCbo2FlWrfC7ORH4HE73FXVHTclWg1XDD4dGHTisYFH/5RzoUU9pfE/FxKd7lwEwcnN8DIbBX0z735zuJvdMLC4zbk9FbXxuRsSp1nqEfvOY04TzMNiPnmVbotNMoUISfIoS70Qy9SSdGzCsCAYeszDtjF4Objb4GEU8baxx3yRUTeW1NAq0JI6/A+3qHIt7s+35ogSY9bBP9vkl7Ro86SzRm2scnODVMHUhOyHwlXPxN6O+Dbl3eFDKrAxOxgXkx+5jhJUbF7rbp3zNqANY3TxR0Wo1UQxjZk1CKoPO59iSPmTqCqMlE0njXd8zAfQtcvRj6fxCAJEy+bSKyxAcBfGkX2O9SwT8PnG9xgNLQeHzgFO6tNyTXGHTOv0EJ4ejgmeIEOWsygpkZlI31UfvBce+EekSxYRGwPuTfSvG9Bqe56QY+YOPvG0OCrY0wEKx5tAzxvGEBaVYbmkjPtt35LC21vLmGXMEoK9r16vr75B7LpVP3uWV79MsCW6i1as46R0IAeBFJ6fhqi0hMq/csrVg9LZtXNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
conda_forge_output_validation: true
